name: "GitHub Metrics"
description: "Get the metrics for a repository"
author: Bullrich
branding:
  icon: activity
  color: blue
inputs:
  GITHUB_TOKEN:
    required: true
    description: The token to access the repo
  repo:
    required: false
    description: The repo to fetch the information from. Defaults to runner
  owner:
    required: false
    description: The owner of the repo to fetch the information from. Defaults to the runner of the action
outputs:
  repo:
    description: "The name of the repo in owner/repo pattern"

runs:
  using: "docker"
  image: "Dockerfile"
