name: "GitHub Metrics"
description: "Get the metrics for a repository"
author: Bullrich
branding:
  icon: activity
  color: blue
inputs:
  GITHUB_TOKEN:
    required: true
    description: The token to access the repo
  repo:
    required: false
    description: Name of the repository in style org/name. Defaults to runner. Can have multiple values separated by comma if it's used for user's metrics
  author:
    required: false
    description: Optional. If we want the metrics of a specific user.
outputs:
  repo:
    description: "The name of the repo in owner/repo pattern"
  pr-report:
    description: "A JSON string with the metrics obtained from the repository PRs"
  issue-report:
    description: "A JSON string with the metrics obtained from the repository issues"

runs:
  using: "docker"
  image: "Dockerfile"
