name: Generate user metrics

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      repo:
        description: "Repositories separated by comma"
        type: string
        required: false
        default: "paritytech/metrics"
      user:
        description: "User"
        type: string
        required: true
        default: "username"

permissions:
  pages: write
  id-token: write

jobs:
  get_metrics:
    runs-on: ubuntu-latest
    name: Get repository metrics
    steps:
      - uses: paritytech/metrics@main
        name: Fetch metrics
        id: metric
        with:
          GITHUB_TOKEN: ${{ github.token }}
          repo: ${{ github.event.inputs.repo }}
          author: ${{ github.event.inputs.user }}
