name: Continuous testing

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        command: [lint, build, test]
    runs-on: ubuntu-latest
    name: running ${{ matrix.command }}
    steps:
      - uses: actions/checkout@v3
      - name: Use node 18
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn run ${{ matrix.command }}

  conclude:
    runs-on: ubuntu-latest
    name: All tests passed
    needs: [test]
    steps:
      - run: echo '### Good job! All the tests passed 🚀' >> $GITHUB_STEP_SUMMARY
