name: Fetch metrics

on: [pull_request]

jobs:
  get_metrics:
    runs-on: ubuntu-latest
    name: Get repository metrics
    steps:
      - uses: paritytech/metrics@pull/stadistics
        name: Fetch polkadot-fellows/runtimes stadistics
        with:
          GITHUB_TOKEN: ${{ github.token }}
          owner: polkadot-fellows
          repo: runtimes
    
      - uses: paritytech/metrics@pull/stadistics
        name: Fetch polkadot-fellows/RFCs 
        with:
          GITHUB_TOKEN: ${{ github.token }}
          owner: polkadot-fellows
          repo: RFCs
    
      - uses: paritytech/metrics@pull/stadistics
        name: Fetch paritytech/polkadot-sdk stadistics
        with:
          GITHUB_TOKEN: ${{ github.token }}
          owner: paritytech
          repo: polkadot-sdk
