# TODO: Remove this file before merging
name: Fetch metrics

on: [pull_request]

jobs:
  get_metrics:
    runs-on: ubuntu-latest
    name: Get repository metrics
    steps:
      - uses: paritytech/metrics@generate-website
        name: Fetch polkadot-fellows/runtimes metrics
        id: metric
        with:
          GITHUB_TOKEN: ${{ github.token }}
          owner: polkadot-fellows
          repo: runtimes
      - run: "ls -la"
